apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenjava-mavenjava
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenjava-mavenjava
  template:
    metadata:
      annotations:
        redeploy: 'true'
      labels:
        app: mavenjava-mavenjava
    spec:
      containers:
      - image: 672072155362.dkr.ecr.us-east-1.amazonaws.com/mavenjava:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 5
        name: mavenjava
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mavenjava-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mavenjava-mavenjava
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: 'true'
  name: my-aws-ingress-class
spec:
  controller: ingress.k8s.aws/alb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/load-balancer-name: mavenjava-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0317ca26c4b68dd91, subnet-0956b1dda20519397
    alb.ingress.kubernetes.io/success-codes: 200-404
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  labels:
    app: app-mavenjava
  name: ingress-mavenjava
spec:
  defaultBackend:
    service:
      name: mavenjava-service
      port:
        number: 8080
  ingressClassName: my-aws-ingress-class
